# Generated by Django 4.1.2 on 2022-10-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isARCamera',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='showARImage',
            field=models.BooleanField(default=True),
        ),
    ]
