# Generated by Django 4.1.2 on 2022-10-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_review', '0002_profile_experiment_two_num_edited_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tellIsAR',
            field=models.BooleanField(default=False),
        ),
    ]
